### ISSUE TITLE
ESRGAN model with Cutblur 

### ISSUE THREAD

**Issue by Darrenxc** [clovaai/cutblur#1]
Hi,
your work is excellent.
I noticed that your paper mentions the GAN model, especially in ESRGAN. However, I didn't find the ESRGAN model in the codes, would you provide the code for ESRGAN model? 
Thank you

**Comment by nmhkahn** [comment]
Hi. Thanks for your interest.
For ESRGAN, we use [xintao/BasicSR](https://github.com/xinntao/BasicSR).
Based on that code, w modify the input layer of the network (to receive enlarged input). To integrate MoA we add `augments.py` and modify `train.py` to give augmented images. Other settings are exactly the same as the ESRGAN official repo, except we doubled the number of iterations.

**Comment by 1999kevin** [comment]
Is it possible to release ESPGAN with your method?
