### ISSUE TITLE
How did you use Cutblur in the GAN setting?

### ISSUE THREAD

**Issue by Vermeille** [clovaai/cutblur#11]
Hi,

It's not clear in the paper and it's not in the repository. Do you cutblur augment the images in the G phase? D phase? both? Something else?

Thank you!

**Comment by nmhkahn** [comment]
Hi. sorry for the late response.
We applied augmentation only in the G phase which somewhat contradicts the recent GAN augmentation works.
I hope that there will be room to improve.
