### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by duweihua** [clovaai/cutblur#13]
when I only use the cutblur data augmentation to retrain the model ,augmens.py in cutblut show ValueError with the rum command : python main.py --model EDSR --augs cutblur --dataset DIV2K_SR --div2k_range 1-800/801-810  --scale 4 --pretrain ./pt/297.pt --dataset_root ./data/DIV2K

![image](https://user-images.githubusercontent.com/43801202/101107574-87750500-360d-11eb-83b5-c71518846f06.png)

**Comment by nmhkahn** [comment]
Hi @duweihua, sorrry for the late response.
Have you solved the problem? if not please reply to the comment :)

**Comment by duweihua** [comment]
Thank you very much, I have solved it.

发件人: Namhyuk Ahn
发送时间: 2020年12月17日 8:46
收件人: clovaai/cutblur
抄送: 华笃伟; Mention
主题: Re: [clovaai/cutblur] image size (#13)

Hi @duweihua, sorrry for the late response.
Have you solved the problem? if not please reply to the comment :)
