### ISSUE TITLE
How to use cutblur on video super resolution?

### ISSUE THREAD

**Issue by coolKeen** [clovaai/cutblur#16]
Thanks for your awesome work!
One question: How to use cutblur on video super resolution in which the input is sequential images?

**Comment by nmhkahn** [comment]
Hi. @coolKeen 
We haven't tried to apply our methods to the video SR; but I think that [VideoMix: Rethinking Data Augmentation for Video Classification](https://arxiv.org/abs/2012.03457) paper somewhat answers your question.
