### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by hank19960918** [clovaai/cutblur#17]
Thanks for your sharing,
I met a problem when I ran the training code.
My comment is like the following python main.py --model EDSR --augs cutblur --dataset DIV2K_SR --div2k_range 1-800/801-810 --scale 2 --dataset_root ./dataset/DIV2K.
![184928958_324842792337548_442282389984753279_n](https://user-images.githubusercontent.com/51408894/118450498-d8456980-b726-11eb-8b16-cee18accc88b.png)
Thanks again

**Comment by nmhkahn** [comment]
This error happens when the alpha arg is equal to 1.0 of cutblur. Though this is definitely the implementation bug, we found that alpha as 0.7 shows the best performance so haven't fixed this.

**Comment by hank19960918** [comment]
Thanks for your immediate reply.
I can run the code after changing the alpha value.
