### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by anandhiray** [clovaai/cutblur#28]
All the links for pretrained model are not working. Can you please give us the new link? Thank you!

**Comment by nmhkahn** [comment]
Hello, I think that gdrive links have expired; I will update these and let you know asap.

**Comment by nmhkahn** [comment]
now you can access through https://drive.google.com/file/d/11lMnMsPv3uZHcKMOw7GAXsyi2suBCkUu/view?usp=sharing

**Comment by anandhiray** [comment]
Thank you very much for the prompt response!
