### ISSUE TITLE
Is the ground truth image modified in cutblur

### ISSUE THREAD

**Issue by Ir1d** [clovaai/cutblur#3]
According to the code it seems that the input is cutblurred and the gt is untouched. However in Eq.(1) in the paper, it seems that the gt is also modified.

![image](https://user-images.githubusercontent.com/10709657/81192371-b9c57200-8fec-11ea-90cd-2f9a604376f1.png)

**Comment by nmhkahn** [comment]
In eq. 1, both x_{HR->LR} and x_{LR->HR} are the input of the network; gt is x_{HR} always. So that the cutblurred region can be inside of the mask (upper) or outside of the mask (below).
