### ISSUE TITLE
No Output and It says 0it [00:00, ?it/s]

### ISSUE THREAD

**Issue by anandhiray** [clovaai/cutblur#30]
When I try to run inference.py for an image in Set14, it doesn't give any output and it says 0it [00:00, ?it/s].

Can you please help figure out what am I doing wrong? Thank you!

**Comment by nmhkahn** [comment]
It probably because `paths` variable does not matched to the "real" paths of images.. you may check `print(paths)` beforehand.

**Comment by anandhiray** [comment]
Thank you! That was it. It is working now.
