### ISSUE TITLE
what is the value of alpha you use in your paper?

### ISSUE THREAD

**Issue by BarCodeReader** [clovaai/cutblur#5]
Hi,

Thanks for your code and idea, quite interesting.
I decide to try to apply on some of the models and test the effectiveness.

May I know what is the value for alpha you used in your paper, for the **cutblur** function?
also, did you verify how different alpha value will affect the effectiveness of cutblur?

Thanks for your help

**Comment by nmhkahn** [comment]
The alpha value used in CutMix and CutBlur controls the mean ratio of the cut regions. So for example, if we set alpha to 0.5, it means that we will perform CutBlur 50% of the input image on average.
Please see Table 6 in our paper (both CutMix and CutBlur parts).
We chose the alpha as 0.7 by the hyperparameter search, but the best value can depend on the task.

**Comment by BarCodeReader** [comment]
Hi,
Thanks for the reply.
I set alpha to 0.3 for my first time,  and the model performs worse, so I changed to 0.5 and seems better.

The alpha=0.5 here, base on your code, will averagely cut a region of 0.5*0.5 = 25% of the input image， instead of 50% of the area.

Thanks for your feedback.

**Comment by jaejun-yoo** [comment]
Hi,

Thanks for your interest to our paper. I just want to add one more comment in addition to Namhyuk's. If you are to really increase the performance, please try MoA as well. With CutBlur, it certainly gives an improvement in many cases and even in the worst case it still can bring you the benefit of preventing the over-applying the function (e.g., over-sharpening or over-smoothing) but it is never the best performance compared to the one with MoA.

**Comment by BarCodeReader** [comment]
Hi,
Thanks for the info.
Yeah I decide to apply them in an additive manner so I can see which one really helps to my task and how much they contributes.

Again, thanks for your idea.
