### ISSUE TITLE
why the way to interpolate is defferent between code and paper? the way in paper is bicubic，however , the way in code is nearest.

### ISSUE THREAD

**Issue by reddandelion217** [clovaai/cutblur#8]
why the way to interpolate is defferent between code and paper? the way in paper is bicubic，however , the way in code is nearest.

**Comment by nmhkahn** [comment]
Hi. Thanks for pointing out.
We initially have used bicubic upsample but found that nearest neighbor upsampling slightly better than the bicubic.
Seems like we've only changed the code, not the description in the paper; we'll fix the paper soon.

**Comment by reddandelion217** [comment]
I got it! thanks for reply so quickly!
