### ISSUE TITLE
There are serious problems in training when changing dataset

### ISSUE THREAD

**Issue by mdswyz** [clovaai/cutblur#9]
I was reproducing cutblur in DIV2K dataset successfully and the cutblur has indeed brought considerable improvement. However, when I changed the face dataset, there was a serious error in the training, and the PSNR value was very low. I can't find the reason for that temporarily. I hope the author can give me some enlightenment.

By the way, this is a awesome project!

Thanks in advance.

**Comment by mdswyz** [comment]
![1](https://user-images.githubusercontent.com/50685067/91649388-271e7680-eaa6-11ea-9c62-100075408f68.png)

**Comment by nmhkahn** [comment]
Not sure what makes the performance too low. Did you run on the face dataset with the exact same setup to the DIV2K? and did you also check the performance of the model w/o cutblur? and what model did you train?

**Comment by mdswyz** [comment]
Thank you for your prompt reply.

Here are the settings for my face dataset：

1. I use 350 images as the training dataset, 10 images as the validation dataset. The HR image size is 360 ∗ 260 pixels, and the downsampling factor is 4, so that the LR image (using Bicubic Degradation Model) size is 90 ∗ 65 pixels.  
2. The RCAN model was used for training. 
3. I also checked the performance of the model w/o cutblur, the result had not changed.

**Comment by nmhkahn** [comment]
> I also checked the performance of the model w/o cutblur, the result had not changed.

meaning RCAN w/o cutblur also suffers the same issue? If true, I think that you'd better try with EDSR first.
Don't know the reason exactly, but I observed that RCAN sometimes goes very unstable so that very careful hyperparameter tuning is needed (especially when start training from x2 pre-trained model).

**Comment by mdswyz** [comment]
RCAN w/o cutblur indeed suffers the same issue when using face dateset, I also use EDSR to train and the same issue still appear. I used the RCAN original code and found that training and testing were OK, so I wonder if your code has some limitations in data preprocessing or other settings.

**Comment by nmhkahn** [comment]
As far as I know, the only different thing is to upsample before feeding to the model (see [L#58](https://github.com/clovaai/cutblur/blob/master/solver.py#L58)). You may first look at how the performance change when removing this code. Of course, you should also remove [DownBlock](https://github.com/clovaai/cutblur/blob/master/model/rcan.py#L71) and adjust the input channel of the first conv layer.

Or if you can share the dataset and code you used it will be helpful to see what's the issue.

**Comment by mdswyz** [comment]
Thank you very much for your prompt reply. I also noticed that the DownBlock module changed the input channel and size before the first convolution layer. I removed this module and changed the input channel of the first convolution layer to 3, and the training is difficult. It should be a preprocessing problem. I will modify the code. If the result is improved, I will share it.

**Comment by mdswyz** [comment]
Hello！
I have been in constant experimentation and found that when the size of the HR image is changed to 360X256 (the corresponding LR image size is 90X64), the code runs ok. The original data size is 360X260 (the corresponding LR image size is 90X65).  I also used the celebA dataset to test your code and found that it runs normally when the image sizes of HR (216X176) and LR (54X44) are both even numbers.
